### ISSUE TITLE
crash when remove_node

### ISSUE THREAD

**Issue by LittlePeng** [chrismoos/hash-ring#13]
#0  0x00007fa300006d4b in ?? ()
#1  0x00007fa3aa83dd96 in quicksort () from /data0/neo_mgw_0.4.4/lib/hash_ring-0.1.6/priv/hash_ring_drv.so
#2  0x00007fa3aa83d026 in hash_ring_remove_node () from /data0/neo_mgw_0.4.4/lib/hash_ring-0.1.6/priv/hash_ring_drv.so
#3  0x00007fa3aa83c295 in hash_ring_drv_output () from /data0/neo_mgw_0.4.4/lib/hash_ring-0.1.6/priv/hash_ring_drv.so
#4  0x00000000004924ef in call_driver_output (c_p=0x7fa3b0ec8f50, flags=2064, prt=0x7fa3d8d40bc0, from=55559696966931,
    list=140341277983642, refp=0x0) at beam/io.c:1768

**Comment by chrismoos** [comment]
This should be fixed now in master.
